### ISSUE TITLE
Create Tests for Update Startup Permissions (IPortal)

### ISSUE THREAD

**Issue by priyanshisharma** [ECellNitrr/EcellWeb2020#3]
Navigate to `backend/iportal` and write appropriate tests for the `update_startup_permissions` API.

Some situations that shall be tested for include
* Startup doesn’t exist
* Request must be made by appropriate user i.e. CDC, Director
* etc.

**Comment by naveennvrgup** [comment]
Let us don't touch Iportal and ca portal part until the main site is done :innocent:
